In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
from pathlib import Path
data_dir = Path("BankData")
csv_files = sorted(list(data_dir.glob("*.csv")) + list(data_dir.glob("*.CSV")))

for file in csv_files:
    df = pd.read_csv(file, nrows=3)
    print(f"\n{'='*20} {file.name} (Columns: {len(df.columns)}) {'='*20}")
    display(df.head(3))

==================== account.csv (Columns: 1) ====================

  account_id;"district_id";"frequency";"date"
0            576;55;"POPLATEK MESICNE";930101
1           3818;74;"POPLATEK MESICNE";930101
2            704;55;"POPLATEK MESICNE";930101

==================== account.csv (Columns: 1) ====================

  account_id;"district_id";"frequency";"date"
0            576;55;"POPLATEK MESICNE";930101
1           3818;74;"POPLATEK MESICNE";930101
2            704;55;"POPLATEK MESICNE";930101

==================== card.csv (Columns: 1) ====================

     card_id;"disp_id";"type";"issued"
0  1005;9285;"classic";931107 00:00:00
1    104;588;"classic";940119 00:00:00
2   747;4915;"classic";940205 00:00:00

==================== card.csv (Columns: 1) ====================

     card_id;"disp_id";"type";"issued"
0  1005;9285;"classic";931107 00:00:00
1    104;588;"classic";940119 00:00:00
2   747;4915;"classic";940205 00:00:00

==================== client.csv (Columns: 1) ====================

  client_id;"birth_number";"district_id"
0                          1;"706213";18
1                           2;"450204";1
2                           3;"406009";1

==================== client.csv (Columns: 1) ====================

  client_id;"birth_number";"district_id"
0                          1;"706213";18
1                           2;"450204";1
2                           3;"406009";1

==================== disp.csv (Columns: 1) ====================

  disp_id;"client_id";"account_id";"type"
0                           1;1;1;"OWNER"
1                           2;2;2;"OWNER"
2                       3;3;2;"DISPONENT"

==================== disp.csv (Columns: 1) ====================

  disp_id;"client_id";"account_id";"type"
0                           1;1;1;"OWNER"
1                           2;2;2;"OWNER"
2                       3;3;2;"DISPONENT"

==================== district.csv (Columns: 1) ====================

  A1;A2;A3;A4;A5;A6;A7;A8;A9;A10;A11;A12;A13;A14;A15;A16
0  1;"Hl.m. Praha";"Prague";1204953;0;0;0;1;1;100...
1  2;"Benesov";"central Bohemia";88884;80;26;6;2;...
2  3;"Beroun";"central Bohemia";75232;55;26;4;1;5...

==================== district.csv (Columns: 1) ====================

  A1;A2;A3;A4;A5;A6;A7;A8;A9;A10;A11;A12;A13;A14;A15;A16
0  1;"Hl.m. Praha";"Prague";1204953;0;0;0;1;1;100...
1  2;"Benesov";"central Bohemia";88884;80;26;6;2;...
2  3;"Beroun";"central Bohemia";75232;55;26;4;1;5...

==================== loan.csv (Columns: 1) ====================

  loan_id;"account_id";"date";"amount";"duration";"payments";"status"
0              5314;1787;930705;96396;12;8033.00;"B"
1             5316;1801;930711;165960;36;4610.00;"A"
2             6863;9188;930728;127080;60;2118.00;"A"

==================== loan.csv (Columns: 1) ====================

  loan_id;"account_id";"date";"amount";"duration";"payments";"status"
0              5314;1787;930705;96396;12;8033.00;"B"
1             5316;1801;930711;165960;36;4610.00;"A"
2             6863;9188;930728;127080;60;2118.00;"A"

==================== order.csv (Columns: 1) ====================

  order_id;"account_id";"bank_to";"account_to";"amount";"k_symbol"
0             29401;1;"YZ";"87144583";2452.00;"SIPO"
1             29402;2;"ST";"89597016";3372.70;"UVER"
2             29403;2;"QR";"13943797";7266.00;"SIPO"

==================== order.csv (Columns: 1) ====================

  order_id;"account_id";"bank_to";"account_to";"amount";"k_symbol"
0             29401;1;"YZ";"87144583";2452.00;"SIPO"
1             29402;2;"ST";"89597016";3372.70;"UVER"
2             29403;2;"QR";"13943797";7266.00;"SIPO"

==================== trans.csv (Columns: 1) ====================

  trans_id;"account_id";"date";"type";"operation";"amount";"balance";"k_symbol";"bank";"account"
0  695247;2378;930101;"PRIJEM";"VKLAD";700.00;700...
1  171812;576;930101;"PRIJEM";"VKLAD";900.00;900....
2  207264;704;930101;"PRIJEM";"VKLAD";1000.00;100...

==================== trans.csv (Columns: 1) ====================

  trans_id;"account_id";"date";"type";"operation";"amount";"balance";"k_symbol";"bank";"account"
0  695247;2378;930101;"PRIJEM";"VKLAD";700.00;700...
1  171812;576;930101;"PRIJEM";"VKLAD";900.00;900....
2  207264;704;930101;"PRIJEM";"VKLAD";1000.00;100...